openapi: 3.0.1
info:
  version: 1.0.0
  title: MAPS TREND API
  description: |-
    MAPS TREND API.  
      You need a `access-token` to test the authorization.
  termsOfService: https://dev.mapstrend.com/terms/
servers:
  - url: https://dev-api.mapstrend.com
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: apiKey
      name: Authorization
      in: header
tags:
  - name: oauth
  - name: client
  - name: script
  - name: apps
paths:
  /oauth:
    get:
      tags:
        - oauth
      summary: Authorization Code 발행
      parameters:
        - name: client_id
          in: query
          description: 고객사 아이디
          required: true
          schema:
            type: string
        - name: redirect_uri
          in: query
          description: 인증코드를 받을 Redirect uri(서비스 등록시 입력된 Redirect URI)
          required: true
          schema:
            type: string
        - name: scope
          in: query
          description: API 권한 ex) client.read,client.write,script.read,script.write
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
  /oauth/token:
    post:
      tags:
        - oauth
      security:
        - BasicAuth: []
      summary: Access Token 발행
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  description: 고객사 아이디
                  type: string
                redirect_uri:
                  description: 서비스 등록시 입력된 Redirect uri(유효성 검증)
                  type: string
                code:
                  description: 이전 단계에서 넘겨 받은 authorization code
                  type: string
              required:
                - client_id
                - redirect_uri
                - code
      responses:
        '201':
          description: Successfully created
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
  /oauth/token/refresh:
    post:
      tags:
        - oauth
      security:
        - BasicAuth: []
      summary: Refresh Token 발행
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  description: 고객사 아이디
                  type: string
                refresh_token:
                  description: Refresh Token
                  type: string
              required:
                - client_id
                - refresh_token
      responses:
        '201':
          description: Successfully created
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
  /client/info:
    get:
      tags:
        - client
      security:
        - BearerAuth: []
      summary: 고객사 정보 요청
      parameters:
        - name: client_id
          in: query
          description: 고객사 아이디
          required: true
          schema:
            type: string
        - name: service_key
          in: query
          description: 서비스 등록시 발행된 Key
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
  /client/period:
    get:
      tags:
        - client
      security:
        - BearerAuth: []
      summary: 고객사 서비스 이용기간 조회
      parameters:
        - name: client_id
          in: query
          description: 고객사 아이디
          required: true
          schema:
            type: string
        - name: service_key
          in: query
          description: 서비스 등록시 발행된 Key
          required: true
          schema:
            type: string
        - name: client_sid
          in: query
          description: 사이트 등록시 발행된 Key
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
    put:
      tags:
        - client
      security:
        - BearerAuth: []
      summary: 고객사 서비스 이용기간 수정
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  description: 고객사 아이디
                  type: string
                refresh_token:
                  description: 서비스 등록시 발행된 Key
                  type: string
                end_date:
                  description: 이용기간 종료날짜(2021-05-13형태/ 종료시간은 start_date 시간대를 따른다)
                  type: string
                client_sid:
                  description: 사이트 등록시 발행된 Key
                  type: string
              required:
                - client_id
                - client_sid
                - refresh_token
                - end_date
      responses:
        '200':
          description: Success
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
  /client/payment:
    post:
      tags:
        - client
      security:
        - BearerAuth: []
      summary: 고객사 인앱결제
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  description: 고객사 아이디
                  type: string
                service_key:
                  description: 서비스 등록시 발행된 Key
                  type: string
                start_date:
                  description: 이용기간 시작날짜(2021-05-01형태/ 시작시간은 결제 시간대를 따른다)
                  type: string
                end_date:
                  description: 이용기간 종료날짜(2021-05-13형태/ 종료시간은 start_date 시간대를 따른다)
                  type: string
                paid_price:
                  description: 결제금액( 0:무료 )
                  type: integer
                client_sid:
                  description: 사이트 등록시 발행된 Key
                  type: string
              required:
                - client_id
                - client_sid
                - service_key
                - start_date
                - end_date
                - paid_price
      responses:
        '201':
          description: Successfully created
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
  /script:
    post:
      tags:
        - script
      security:
        - BearerAuth: []
      summary: 스크립트 추가 요청
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  description: 고객사 아이디
                  type: string
                client_sid:
                  description: 사이트 등록시 발행된 Key
                  type: string
                service_key:
                  description: 서비스 등록시 발행된 Key
                  type: string
                script_src:
                  description: 스크립트 URL
                  type: array
                  items:
                    oneOf:
                      - $ref: '#/definitions/scriptsrc'
                      - $ref: '#/definitions/scriptsrc2'
                script_init:
                  description: 서비스 등록시 설정키값
                  type: array
                  items:
                    oneOf:
                      - $ref: '#/definitions/scriptinit'
                      - $ref: '#/definitions/scriptinit2'
                      - $ref: '#/definitions/scriptinit3'
              required:
                - client_id
                - client_sid
                - service_key
                - script_src
      responses:
        '201':
          description: Successfully created
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
  /script/{script_id}:
    put:
      tags:
        - script
      security:
        - BearerAuth: []
      summary: 스크립트 수정 요청
      parameters:
        - name: script_id
          in: path
          description: script_id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  description: 고객사 아이디
                  type: string
                client_sid:
                  description: 사이트 등록시 발행된 Key
                  type: string
                service_key:
                  description: 서비스 등록시 발행된 Key
                  type: string
                script_src:
                  description: 스크립트 URL
                  type: array
                  items:
                    oneOf:
                      - $ref: '#/definitions/scriptsrc'
                      - $ref: '#/definitions/scriptsrc2'
                script_init:
                  description: 서비스 등록시 설정키값
                  type: array
                  items:
                    oneOf:
                      - $ref: '#/definitions/scriptinit'
                      - $ref: '#/definitions/scriptinit2'
                      - $ref: '#/definitions/scriptinit3'
              required:
                - client_id
                - client_sid
                - service_key
                - script_src
      responses:
        '200':
          description: Success
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
    delete:
      tags:
        - script
      security:
        - BearerAuth: []
      summary: 스크립트 삭제 요청
      parameters:
        - name: script_id
          in: path
          description: 스크립트 추가요청시 발급된 ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '401':
          description: 유효하지 않은 요청
        '403':
          description: 권한이 없습니다
        '422':
          description: 필수 피라메터 누락
        '500':
          description: 서버에러
  /apps/notification:
    post:
      tags:
        - apps
      security:
        - BearerAuth: []
      summary: 개별 푸시 발송 요청
      parameters:
        - name: client_id
          in: query
          description: 고객아이디
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content: {}
        '405':
          description: Invalid Input
          content: {}
  /apps/landing:
    post:
      tags:
        - apps
      security:
        - BearerAuth: []
      summary: 랜딩뷰 추천 상품
      parameters:
        - name: client_id
          in: query
          description: 고객아이디
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content: {}
        '405':
          description: Invalid Input
          content: {}
  /apps/retarget:
    post:
      tags:
        - apps
      security:
        - BearerAuth: []
      summary: 리타겟 추천 상품
      parameters:
        - name: client_id
          in: query
          description: 고객아이디
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content: {}
        '405':
          description: Invalid Input
          content: {}
definitions:
  token:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      expires_date:
        type: string
      refresh_expires_date:
        type: string
      client_id:
        type: string
      issued_date:
        type: string
    required:
      - access_token
      - refresh_token
      - expires_date
      - refresh_expires_date
      - client_id
      - issued_date
  scriptsrc:
    type: string
    example: https://yourdomain-script.com/sample-script.js
  scriptsrc2:
    type: string
    example: https://yourdomain-script.com/sample-script.js
  scriptinit:
    type: object
    properties:
      key1:
        type: string
        description: name of the object
        example: value
  scriptinit2:
    type: object
    properties:
      key2:
        type: string
        description: name of the object
        example: value
  scriptinit3:
    type: object
    properties:
      key3:
        type: string
        description: name of the object
        example: value
